### ISSUE TITLE
Show red Not Activated banner bar

### ISSUE THREAD

**Issue by reactor10** [reactor10/figroll-app#25]
If a user has not activated their account a red banner bar should say their account has not been activated

**Comment by drydenwilliams** [comment]
Need to return `ExpiresAt` from `/auth/login`

**Comment by reactor10** [comment]
Endpoint `/users/me` now returns:

```json
{
    "id": "75ed0db7-1ab5-41b6-b091-5a47201720b9",
    "activated": true,
    "email": "byron@112percent.com",
    "firstName": "Byron",
    "lastName": "Williams"
}
```

**Comment by reactor10** [comment]
Send a HTTP POST to `/users/resend-activation` to resend the reset activation
