### ISSUE TITLE
Password Validation allows any length Password

### ISSUE THREAD

**Issue by reactor10** [reactor10/figroll-app#8]
**Actual**
During registration I fill in the following details:

First Name: Byron
Last Name: Williams
Email: byron+test@112percent.com
Password: short

A 400 is returned from the API (as expected) but no error is shown.

**Expected**

- [ ] Errors to be reported back from the API and shown to the user

**Comment by drydenwilliams** [comment]
Never enjoyed receiving a bug more than this! Will get on it as soon as :D

**Comment by drydenwilliams** [comment]
What do you mean by the second checkbox about the API?
